---

# Instal Metasploit
- name: Create directory for Metasploit
  file:
    path: "/root/msf"
    state: directory
    mode: "0755"

- name: Download metasploit
  get_url:
    url: https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb
    dest: /root/msf/msfinstall
    mode: '0755'

- name: Run msfinstall script
  shell: "./msfinstall"
  args:
    chdir: /root/msf

...