---
# This is a role for setting up the client.

- name: Create alias for server
  lineinfile:
    path: '/etc/hosts'
    line: '192.168.20.5 server'

- name: Create alias for client 2
  lineinfile:
    path: '/etc/hosts'
    line: '192.168.30.3 client2'

# - name: Install packages
#   apt:
#     pkg:
#      - nmap
#      - hydra
#      - medusa
#     update_cache: yes

- name: Update apt cache
  apt:
    update_cache: yes

# Install wireshark and allow non-superusers capture packets
# - name: Set debconf answer for non-superusers
#   debconf:
#     name: wireshark-common
#     question: wireshark-common/install-setuid
#     value: true
#     vtype: boolean

# - name: Install Wireshark package
#   apt:
#     name: wireshark
#     state: present


# - name: Add passwords file to the home directory
#   copy:
#     src: passlist.txt
#     dest: /home/user/passlist.txt
#     owner: user
#     mode: 0644

- name: Install xfce4 and xfce4-goodies
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - xfce4
    - xfce4-goodies

- name: Choose lightdm as the default display manager
  expect:
    command: dpkg-reconfigure lightdm
    responses:
      'Default display manager:': lightdm

- name: Install tightvncserver
  become: true
  apt:
    name: tightvncserver
    state: present

- name: Run vncserver and configure password
  expect:
    command: vncserver
    responses:
      'Password:': password
      'Verify:': password
      'Would you like to enter a view-only password (y/n)?': n

- name: Reboot the system
  become: true
  command: reboot

- name: Run vncserver again
  expect:
    command: vncserver
    responses:
      'Password:': password
      'Verify:': password
      'Would you like to enter a view-only password (y/n)?': n


...
