---
# This is a role for setting up the client.

- name: Create alias for server
  lineinfile:
    path: '/etc/hosts'
    line: '192.168.20.5 server'

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install packages
  become: true
  apt:
    name: 
      - firefox
      - wireshark
    state: present

- name: Create script file
  copy:
    src: Basic_authen/basic_auth.sh
    dest: /opt/basic_auth.sh
    mode: "0755"

- name: Create cron job for basic authen
  ansible.builtin.cron:
    name: Run basic_auth.sh every minute
    minute: "*/1"
    job: "/opt/basic_auth.sh"

# Include Config GUI
- include_tasks: Config_GUI.yml

# Include Config John
- include_tasks: Config_John.yml

# Include Config metasploit
- include_tasks: Config_metasploit.yml

...
