---

- name: Set Python interpreter to Python 3
  set_fact:
    ansible_python_interpreter: /usr/bin/python3

- name: Install python3
  apt:
    pkg:
     - php-mysql
     - python3
     - python3-pip
     - python3-mysqldb
     - unzip
    update_cache: yes

- name: Set Python interpreter to Python 3
  set_fact:
    ansible_python_interpreter: /usr/bin/python3

- name: Update short_open_tag
  lineinfile:
    path: /etc/php/7.4/apache2/php.ini
    regexp: '^short_open_tag = Off'
    line: 'short_open_tag = On'

- name: Restart Apache2 service
  systemd:
    name: apache2
    state: restarted

- name: Secure MySQL Installation
  mysql_user:
    login_user: root
    login_password: ""
    user: root
    host: localhost
    password: "{{ mysql_root_password }}"
    priv: "*.*:ALL,GRANT"
    state: present

- name: Create MySQL User
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    user: "{{ mysql_user }}"
    host: localhost
    password: "{{ mysql_user_password }}"
    priv: "*.*:ALL"
    state: present

- name: Create Assignment.zip
  copy:
    dest: /var/www/html/super_secret/StudentManagement.zip
    src: MySQL/StudentManagement.zip

- name: Unzip the file
  unarchive:
    src: /var/www/html/super_secret/StudentManagement.zip
    dest: /var/www/html/super_secret/
    remote_src: yes

- name: Remove file StudentManagement.zip
  file:
    path: /var/www/html/super_secret/StudentManagement.zip
    state: absent
  ignore_errors: True

- name: Create student_management.sql
  copy:
    dest: /opt/student_management.sql
    src: MySQL/student_management.sql

- name: Create Database
  mysql_db:
    name: student_management
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  ignore_errors: True

- name: Import SQL file
  mysql_db:
    name: "student_management"
    state: import
    target: "/opt/student_management.sql"
    login_user: root
    login_password: "{{ mysql_root_password }}"
  ignore_errors: True

...
