---
# This is a role for setting up the server.

- name: Create alias for client
  lineinfile:
    path: '/etc/hosts'
    line: '192.168.30.5 client'

- name: Add user and set password
  user:
    name: '{{ username }}'
    password: '{{ password | password_hash(''sha512'') }}'
    shell: '/bin/bash'

- name: Remove sudo access for user
  lineinfile:
    dest: /etc/sudoers
    state: absent
    regexp: "^user.*"

- name: Install packages
  apt:
    pkg:
     - telnetd
     - apache2
     - libapache2-mod-php
     - mysql-server
     - mysql-client
     - vsftpd
    update_cache: yes

- name: Start vsftpd
  systemd:
    name: vsftpd
    state: started

# may need some change here !!!
- name: Create privilege escalation vulnerability
  lineinfile:
    path: /etc/sudoers
    line: '{{ username }} ALL=(ALL) NOPASSWD:ALL'

# Include Config Apache2
- include_tasks: Config_Apache2.yml

# Include Config John
- include_tasks: Config_John.yml

...
