---
# This is a role for setting up the server.

- name: Add user and set password
  user:
    name: '{{ username }}'
    password: '{{ password | password_hash(''sha512'') }}'
    shell: '/bin/bash'

- name: Install packages
  apt:
    pkg:
     - telnetd
     - apache2
    update_cache: yes

- name: Create privilege escalation vulnerability
  lineinfile:
    path: /etc/sudoers
    line: '{{ username }} ALL=(ALL) NOPASSWD:ALL'

# - name: Place flag
#   copy:
#     dest: '/home/{{ username }}/flag.txt'
#     owner: '{{ username }}'
#     content: '{{ flag }}'
#     mode: '0600'

# - name: Place second flag
#   copy:
#     dest: '/root/flag.txt'
#     owner: root
#     content: '{{ flag_2 }}'
#     mode: '0600'

- name: Create alias for client
  lineinfile:
    path: '/etc/hosts'
    line: '192.168.30.5 client'

- name: Create alias for client 2
  lineinfile:
    path: '/etc/hosts'
    line: '192.168.30.3 client2'

#####
- name: Start Apache service
  service:
    name: apache2
    state: started
###################################################################
# - name: Create secret directory
#   file:
#     path: /var/www/html/secret
#     state: directory

# - name: Create secret index.html file
#   copy:
#     dest: /var/www/html/secret/index.html
#     src: index1.html

# - name: Configure secret Apache site
#   copy:
#     dest: /etc/apache2/sites-enabled/001-secret.conf
#     src: 001-secret.conf
#############################################################
- name: Create super_secret directory
  file:
    path: /var/www/html/super_secret
    state: directory

- name: Create super_secret index.html file
  copy:
    dest: /var/www/html/super_secret/index.html
    src: index2.html

- name: Configure secret Apache site
  copy:
    dest: /etc/apache2/sites-enabled/001-super_secret.conf
    src: 001-super_secret.conf
###################################################################
# - name: Specify username and password of user
#   expect:
#     command: htpasswd -c /etc/apache2/.htaccess_secret user
#     responses:
#       "New password:": "Password123"
#       "Re-type new password:": "Password123"

- name: Specify username and password of user2
  expect:
    command: htpasswd -c /etc/apache2/.htaccess_super_secret user2
    responses:
      "New password:": "{{ flag_1 }}"
      "Re-type new password:": "{{ flag_1 }}"

- name: Restart Apache service
  service:
    name: apache2
    state: restarted

...
