- name: Create script file
  copy:
    src: basic_auth.sh
    dest: /opt/basic_auth.sh
    mode: "0755"

- name: Create cron job
  ansible.builtin.cron:
    name: Run basic_auth.sh every minute
    minute: "1"
    job: "/opt/basic_auth.sh"