---

- name: disable qxl
  hosts:
      - routers
      - hosts
  gather_facts: yes
  become: yes
  tasks:
      - include_role:
            name: kypo-disable-qxl
        when: ansible_os_family == 'Debian'

- name: set up server
  hosts: server
  become: yes
  roles:
    - name: server

- name: set up client
  hosts: client
  become: yes
  roles:
    - name: kypo-user-access
      kypo_user_access_username: user
      kypo_user_access_password: Password123
      kypo_user_access_sudo: True
    - name: client

- name: setup logging bash
  hosts:
    - hosts
    - routers
  gather_facts: yes
  become: yes
  roles:
    - role: sandbox-logging-forward
      slf_destination: '{{ hostvars["man"].ansible_host }}'
      slf_sandbox_id: "{{ kypo_global_sandbox_id }}"
      slf_sandbox_name: '{{ kypo_global_sandbox_name }}'
      slf_pool_id: '{{ kypo_global_pool_id }}'
    - role: sandbox-logging-bash

...
